apiVersion: v1
kind: PersistentVolume
metadata:
  name: pv20
spec:
  accessModes:
  - ReadWriteOnce
  capacity:
    storage: 100Gi
  claimRef:
    apiVersion: v1
    kind: PersistentVolumeClaim
    name: pvc
    namespace: opvn
  persistentVolumeReclaimPolicy: Retain
  qcloudCbs:
    cbsDiskId: disk-0mr48u75
    fsType: ext4
  storageClassName: cbs
  volumeMode: Filesystem

